ls:
  src:
    .dir: kebab-case
    .js: kebab-case
    .ts: kebab-case
    .tsx: kebab-case
    .d.ts: kebab-case
    .less: kebab-case
  src/models: 
    .dir: kebab-case
    .ts: camelCase
ignore:
  - .babelrc.js
  - .eslintrc.js
  - .prettierrc.js
  - .github
  - .git
  - dist
  - node_modules
  - src/.umi
  - src/.umi-production
